name: firebase_chatapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #Firebase Packages
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.0
  firebase_core: ^0.5.0
  
  #Resourceful Packages
  google_sign_in: ^4.5.1
  rxdart: ^0.24.1
  shared_preferences: ^0.5.8
  image_picker: ^0.6.7+7
  
  #UI Packages
  lottie: ^0.6.0
  persistent_bottom_nav_bar: ^1.5.5
  flutter_signin_button: ^1.0.0
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.2
  flutter_secure_storage: ^4.2.0


  #encryption 
  encrypt: ^4.1.0
  simple_rsa: ^0.0.5
  rsa_encrypt: ^1.0.5

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
